
# --- Servidor ---
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/vetclinic_db
#spring.datasource.url=jdbc:postgresql://localhost:5432/pruebaVet

# Usuario y contraseña que creaste en PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
# create-droprea las tablas al iniciar, las borra al cerrar (
# update actualiza las tablas si hay cambios en las clases
# validate  solo valida que las tablas existan, no crea nada
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola el SQL que genera Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=vetclinicdb
